build:
  stage: build
  image: node:18.16.1
  script:
    - yarn install
    - yarn run build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --region us-east-1 s3 sync dist/ s3://go-renty-front-bucket/
    - aws --region us-east-1 s3 sync src/ s3://go-renty-front-bucket/
